add a proposal of Smart Coding benchmark suite
kubeedge/ianvs pull request #120
Opened 2024-07-17 14:50 UTC by safe-b

Smart Coding benchmark suite: built on KubeEdge-lanvs

What type of PR is this?
/kind test
/kind design

What this PR does / why we need it:
The PR is a proposal to enhance a dataset by annotating the core code of the classic Python project, and then add project problems and App projects, etc., to finally complete the creation of the dataset and conduct test evaluation.
Which issue(s) this PR fixes:
[#98 ](https://github.com/kubeedge/ianvs/issues/98)
Fixes #

2024-07-18 10:30 UTC, hsj576 commented
The PR should further elaborate on how to implement this feature in Ianvs.

2024-07-18 11:27 UTC, MooreZheng commented on docs/proposals/test-reports/Smart Coding benchmark suite Proposal.md
Good to see the proposal and there are two advices. 
1. Putting ianvs integration at the final stage would be risky for this project. The integration shall be started asap. 
2. It is not clear how would it be related to the SIG AI project. An architecture with ianvs is needed. E.g., considering dataset, metric in TestEnv Manager. You might want to take a look at https://github.com/kubeedge/ianvs/pull/122/files

2024-09-20 14:28 UTC, MooreZheng reviewed
The main concern has been fixed. Though there is question on the targeted learning tasks, overall it looks fine to me.

2024-09-20 14:28 UTC, MooreZheng commented
/lgtm

2024-10-14 02:59 UTC, MooreZheng requested changes
There is a CI issue remains to be solved 

```
Run pylint '/home/runner/work/ianvs/ianvs/core'
************* Module core.testcasecontroller.algorithm.paradigm.singletask_learning.singletask_learning_active_boost
core/testcasecontroller/algorithm/paradigm/singletask_learning/singletask_learning_active_boost.py:66:4: R0917
************* Module core.testenvmanager.dataset.dataset
core/testenvmanager/dataset/dataset.py:119:4: R0917: Too many positional arguments (8/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:206:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:213:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:246:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:285:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:329:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:368:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)

-----------------------------------
Your code has been rated at 9.95/[10](https://github.com/kubeedge/ianvs/actions/runs/10814126756/job/30437126717?pr=120#step:5:11)

Error: Process completed with exit code 8.
```

2024-10-26 03:22 UTC, MooreZheng requested changes
There are also CI issues that remain to be solved see https://github.com/kubeedge/ianvs/actions/runs/11524309022/job/32095357988?pr=159

For example 
'''
Run if [ "3.7" = "3.9" ]; then
************* Module core.testenvmanager.dataset.dataset
core/testenvmanager/dataset/dataset.py:22:0: C0301: Line too long (106/100) (line-too-long)
core/testenvmanager/dataset/dataset.py:22:0: E06[11](https://github.com/kubeedge/ianvs/actions/runs/11524309022/job/32095357988?pr=159#step:5:12): No name 'JsonlDataParse' in module 'sedna.datasources' (no-name-in-module)
core/testenvmanager/dataset/dataset.py:22:0: E0611: No name 'JSONMetaDataParse' in module 'sedna.datasources' (no-name-in-module)
core/testenvmanager/dataset/dataset.py:28:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
core/testenvmanager/dataset/dataset.py:19:0: W0611: Unused import json (unused-import)

-----------------------------------
Your code has been rated at 9.92/10

Error: Process completed with exit code 30.
'''

2024-10-31 02:34 UTC, hsj576 approved these changes
/lgtm

2024-10-31 08:14 UTC, MooreZheng commented
/lgtm

2024-10-31 08:15 UTC, MooreZheng commented
/approve

2024-10-31 08:15 UTC, MooreZheng approved these changes
Concerns to the proposal are fixed

2024-10-31 08:16 UTC, merged

2026-02-04 02:04 UTC, MooreZheng commented
Related issue and PR: https://github.com/kubeedge/ianvs/issues/98 https://github.com/kubeedge/ianvs/pull/120 https://github.com/kubeedge/ianvs/pull/159