Feat: Development of Federated Incremental Learning for Label Scarcity: Base on KubeEdge-Ianvs
kubeedge/ianvs pull request #143
Opened 2024-09-08 07:40 UTC by Yoda-wu

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR add two main feature: 
- federated learning paradigm
- federated class incremental learning paradigm

Besides this PR also add the example of these two paradigm.

**Which issue(s) this PR fixes**:
related issue: https://github.com/kubeedge/ianvs/issues/97

Fixes #

2024-10-14 03:10 UTC, MooreZheng requested changes
There are three CI issues that remain to be resolved, mainly for Pylint, see https://github.com/kubeedge/ianvs/actions/runs/11268242806

2024-10-14 03:27 UTC, Yoda-wu commented
> There are three CI issues that remain to be resolved, mainly for Pylint, see https://github.com/kubeedge/ianvs/actions/runs/11268242806

Thanks for comment!, but i think the linked action is not my pr's action.
I have some question about Pylint, In Pylint(3.9) it got error:
```
Run pylint '/home/runner/work/ianvs/ianvs/core'
************* Module core.testenvmanager.dataset.dataset
core/testenvmanager/dataset/dataset.py:124:4: R091[7](https://github.com/kubeedge/ianvs/actions/runs/11320404587/job/31477907116#step:5:8): Too many positional arguments (8/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:237:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:244:4: R0[9](https://github.com/kubeedge/ianvs/actions/runs/11320404587/job/31477907116#step:5:10)17: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:291:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:349:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:422:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
core/testenvmanager/dataset/dataset.py:492:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
************* Module core.testcasecontroller.algorithm.paradigm.singletask_learning.singletask_learning_active_boost
core/testcasecontroller/algorithm/paradigm/singletask_learning/singletask_learning_active_boost.py:66:4: R0917: Too many positional arguments (7/5) (too-many-positional-arguments)
```
which is not my pr's feature. I try to add  disabel too-many-positional-arguments and it turn outs that Pylint(3.7,3.8) can't recognize this argument.
```
Run pylint '/home/runner/work/ianvs/ianvs/core'
************* Module core.testenvmanager.dataset.dataset
core/testenvmanager/dataset/dataset.py:119:0: W0012: Unknown option value for 'disable', expected a valid pylint message and got 'too-many-positional-arguments' (unknown-option-value)
core/testenvmanager/dataset/dataset.py:20[7](https://github.com/kubeedge/ianvs/actions/runs/11137579503/job/31477583235?pr=143#step:5:8):0: W0012: Unknown option value for 'disable', expected a valid pylint message and got 'too-many-positional-arguments' (unknown-option-value)
core/testenvmanager/dataset/dataset.py:215:0: W0012: Unknown option value for 'disable', expected a valid pylint message and got 'too-many-positional-arguments' (unknown-option-value)
core/testenvmanager/dataset/dataset.py:249:0: W0012: Unknown option value for 'disable', expected a valid pylint message and got 'too-many-positional-arguments' (unknown-option-value)
core/testenvmanager/dataset/dataset.py:2[8](https://github.com/kubeedge/ianvs/actions/runs/11137579503/job/31477583235?pr=143#step:5:9)8:0: W0012: Unknown option value for 'disable', expected a valid pylint message and got 'too-many-positional-arguments' (unknown-option-value)
core/testenvmanager/dataset/dataset.py:334:0: W0012: Unknown option value for 'disable', expected a valid pylint message and got 'too-many-positional-arguments' (unknown-option-value)
```

2024-10-22 10:51 UTC, chenhaorui0768 requested changes

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/fed_ci_match/algorithm/agumentation.py
> +    def augment_for_svhn(self, images: np.ndarray):
Unused dataset augmentation code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/fed_ci_match/algorithm/agumentation.py
> +        elif self.dataset_name == "stl10":
Unused dataset augmentation code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on core/testcasecontroller/algorithm/paradigm/federated_learning/federated_learning.py
> +        # self.init_client()
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/fedavg/algorithm/aggregation.py
> +        # print(next(iter(clients)).weights)
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/fedavg/algorithm/basemodel.py
> +            # pred = tf.cast(tf.argmax(logits, axis=1), tf.int32)
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/glfc/algorithm/agumentation.py
> +        elif self.dataset_name == 'svhn':
Unused dataset augmentation code

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/glfc/algorithm/basemodel.py
> +        # print(self.encode_model.get_weights())
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/glfc/algorithm/basemodel.py
> +        # keras.initializers.glorot_uniform()
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/glfc/algorithm/model.py
> +# from keras import layers, Sequential
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/fci_ssl/glfc/algorithm/proxy_server.py
> +                        # if iter == self.Iteration - 1:
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/federated_class_incremental_learning/fedavg/algorithm/basemodel.py
> +            # prob = tf.nn.softmax(logits, axis=1)
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/federated_class_incremental_learning/fedavg/algorithm/network.py
> +        # print(type(self.feature))
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/federated_class_incremental_learning/fedavg/algorithm/resnet.py
> +# import keras
Annotated code should be removed

2024-10-22 10:51 UTC, chenhaorui0768 commented on examples/cifar100/utils.py
> +    # train_cnt = 0
Annotated code should be removed

2024-10-22 16:10 UTC, MooreZheng commented
/lgtm

2024-10-22 16:10 UTC, MooreZheng commented
@hsj576 might want to have a look at this project

2024-10-26 01:44 UTC, hsj576 requested changes
The EGG-INFO file should not be uploaded to the github repository.

2024-10-26 03:00 UTC, Yoda-wu commented
> The EGG-INFO file should not be uploaded to the github repository.

Sorry about that， i remove it  right now

2024-10-28 02:38 UTC, chenhaorui0768 commented
/lgtm

2024-10-28 03:04 UTC, MooreZheng reviewed
This pull request contains 8 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. In the final stage, @Yoda-wu can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

2024-10-28 04:08 UTC, Yoda-wu commented
> This pull request contains 8 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. In the final stage, @Yoda-wu can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

thank you for the advice! i will squash the commits if this pr have nothing to change. Looking forward to more reviews from @MooreZheng @chenhaorui0768 @hsj576. Due to the deadline of OSPP, please feel free to comment so i can fix it asap~

2024-10-29 11:08 UTC, hsj576 commented
/lgtm

2024-10-29 16:04 UTC, MooreZheng commented
/lgtm

2024-10-29 16:05 UTC, MooreZheng commented
/approve

2024-10-29 16:05 UTC, MooreZheng approved these changes
All concerns are fixed. Well done @Yoda-wu

2024-10-29 16:06 UTC, merged