OSPP: Implementation of Domain-Specific Large Model Benchmarking Based on KubeEdge-Ianvs
kubeedge/ianvs pull request #144
Opened 2024-09-09 16:59 UTC by IcyFeather233

This PR is the implementation of https://github.com/kubeedge/ianvs/issues/95

2024-09-11 05:50 UTC, hsj576 requested changes
The "print" in the code should be replaced by "LOGGER.info" (from core.common.log import LOGGER ").

2024-09-11 14:23 UTC, IcyFeather233 commented
> The "print" in the code should be replaced by "LOGGER.info" (from core.common.log import LOGGER ").

@hsj576 Thank you for your advice! Now they are all replaced.

2024-09-20 15:01 UTC, MooreZheng requested changes
Rebases are needed. 

1. There is a file with conflicts like docs/proposals/scenarios/llm-benchmarks/llm-benchmarks.md that needs to take care of. e.g., using rebase https://liwt31.github.io/2019/12/25/merge_rebase/.  

2. all commits need sign-off, which can also be solved by using rebase 

> Commit sha: [9b7f9c5](https://github.com/kubeedge/ianvs/pull/144/commits/9b7f9c51495b06557ae5f8f1d10f57f55df6dc22), Author: IcyFeather, Committer: IcyFeather; The sign-off is missing.
> Commit sha: [ce9f470](https://github.com/kubeedge/ianvs/pull/144/commits/ce9f470f0f4614fbdf06d90f857a6457ae9cddd3), Author: IcyFeather, Committer: IcyFeather; The sign-off is missing.


> To add your Signed-off-by line to every commit in this branch:
> 
> Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> In your local branch, run: git rebase HEAD~11 --signoff
> Force push your changes to overwrite the branch: git push --force-with-lease origin dev

2024-10-14 03:13 UTC, MooreZheng requested changes
> Rebases are needed.
> 
> 1. There is a file with conflicts like docs/proposals/scenarios/llm-benchmarks/llm-benchmarks.md that needs to take care of. e.g., using rebase https://liwt31.github.io/2019/12/25/merge_rebase/.
> 2. all commits need sign-off, which can also be solved by using rebase
> 
> > Commit sha: [9b7f9c5](https://github.com/kubeedge/ianvs/pull/144/commits/9b7f9c51495b06557ae5f8f1d10f57f55df6dc22), Author: IcyFeather, Committer: IcyFeather; The sign-off is missing.
> > Commit sha: [ce9f470](https://github.com/kubeedge/ianvs/pull/144/commits/ce9f470f0f4614fbdf06d90f857a6457ae9cddd3), Author: IcyFeather, Committer: IcyFeather; The sign-off is missing.
> 
> > To add your Signed-off-by line to every commit in this branch:
> > Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> > In your local branch, run: git rebase HEAD~11 --signoff
> > Force push your changes to overwrite the branch: git push --force-with-lease origin dev

Reminder: There are three CI issues that remain to be resolved, mainly for Pylint, see https://github.com/kubeedge/ianvs/actions/runs/11268242806

2024-10-14 10:48 UTC, IcyFeather233 commented
@MooreZheng The similar pylint issues are described in https://github.com/kubeedge/ianvs/issues/152

To solve this, sedna and ianvs need to corporate. We discussed this problem in the last week zoom meeting, and it seems that it should be discussed more to find a final solution.

2024-10-22 16:12 UTC, MooreZheng commented
@hsj576 might also want to review this project

2024-10-24 09:13 UTC, MooreZheng requested changes
Looks fine, but we need to refine the Chinese words as in English.

2024-10-24 09:13 UTC, MooreZheng commented on examples/government/singletask_learning_bench/objective/testenv/acc.py
> +    # 检查输入是否为空或只包含非字母字符
In the acc.py, need to replace Chinese characters with English.

2024-10-24 09:13 UTC, MooreZheng commented on examples/government/singletask_learning_bench/subjective/testenv/llm_judgement.py
> +    # 使用正则表达式匹配综合得分及其分数
In the llm_judgement.py, we need to replace Chinese characters with English.

2024-10-24 09:13 UTC, MooreZheng commented on examples/llm_simple_qa/README.md
> +`train_data/data.jsonl` is empty, and the `test_data/data.jsonl` is as follows:
As the following examples, we also need to replace questions in Chinese with those in English.

2024-10-24 09:13 UTC, MooreZheng commented on examples/llm_simple_qa/testenv/acc.py
> +    # 检查输入是否为空或只包含非字母字符
In the acc.py in examples, need to replace Chinese comments into English.

2024-10-27 13:27 UTC, IcyFeather233 commented
@MooreZheng I have changed Chinese words to English

2024-10-28 02:58 UTC, MooreZheng commented
Overall it looks fine. Any comment from @hsj576 before merging?

2024-10-28 02:58 UTC, MooreZheng requested changes
Good. There is only one Chinese statement right now and we are very close to the final version.

Currently, this pull request contains 25 commits, which can make maintenance difficult, considering the number of contributors, pull requests, and their commits. In the final stage, @IcyFeather233 can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

2024-10-28 02:58 UTC, MooreZheng commented on examples/government/singletask_learning_bench/subjective/testenv/llm_judgement.py
> +    match = re.search(r"'综合得分': (\d+)", input_str)
In the re.search of llm_judgement.py, we need to replace Chinese characters with English.

2024-10-28 04:42 UTC, IcyFeather233 commented
@MooreZheng All commits merged into one, and all Chinese words changed to English

2024-10-28 07:03 UTC, MooreZheng commented
/lgtm

2024-10-29 16:12 UTC, MooreZheng requested changes
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/kubeedge/ianvs/pull/144/conflicts) or the  to resolve conflicts.
Conflicting files
core/testenvmanager/dataset/dataset.py

2024-10-30 05:23 UTC, IcyFeather233 commented
@MooreZheng conflicts are resolved

2024-10-30 12:46 UTC, MooreZheng requested changes
Conflicts still exists 

This branch has conflicts that must be resolved
Use the [web editor](https://github.com/kubeedge/ianvs/pull/144/conflicts) or the  to resolve conflicts.
Conflicting files
core/testenvmanager/dataset/dataset.py

2024-10-30 14:02 UTC, MooreZheng commented
Now conflicts have been solved

2024-10-30 14:02 UTC, MooreZheng commented
/lgtm

2024-10-30 14:10 UTC, hsj576 commented
/lgtm

2024-10-30 14:11 UTC, MooreZheng commented
/approve

2024-10-30 14:12 UTC, merged

2024-10-30 14:12 UTC, MooreZheng approved these changes
All concerns are fixed. Well done!

2026-01-31 01:47 UTC, MooreZheng commented
Related issue and PR:  
Phase 1 Gov LLM https://github.com/kubeedge/ianvs/issues/95 https://github.com/kubeedge/ianvs/pull/113 https://github.com/kubeedge/ianvs/pull/144
Phase 2 Gov RAG https://github.com/kubeedge/ianvs/issues/177 https://github.com/kubeedge/ianvs/pull/186 https://github.com/kubeedge/ianvs/pull/196