add Impl for llm edge benchmark suite
kubeedge/ianvs pull request #150
Opened 2024-09-24 14:59 UTC by XueSongTap

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

add Impl for llm edge benchmark suite

**Which issue(s) this PR fixes**:

https://github.com/kubeedge/ianvs/pull/127

2024-10-14 03:22 UTC, MooreZheng requested changes
There are CI issues that remain to be resolved, see https://github.com/kubeedge/ianvs/actions/runs/11179368172?pr=150

2024-10-24 08:51 UTC, MooreZheng requested changes
The CI issues are properly tackled. As discussed at the routine meeting, suggestions would be 
1. Might show a final result (e.g., ranking) in the PR;
2. Replace the Chinese statements into English; 
3. Replace the print with loggers;

2024-10-26 01:50 UTC, hsj576 requested changes
The Chinese prompt should be removed.

2024-10-26 01:50 UTC, hsj576 commented on examples/llm-edge-benchmark-suite/single_task_bench/testenv/prefill_latency.py
> +    #TODO 前面所有歌predict_dict 的结果，可以通过下面拿出来，我想把计算平均的过程放在这里，帮我实现
The Chinese prompt should be removed.

2024-10-26 07:18 UTC, XueSongTap commented
@hsj576 Could you please review this PR? I've made several documentation and configuration updates:

- Comment cleanup in basemodel.py
- Configuration parameter adjustments
- Documentation improvements in README, including remove chinese part

Here's  screenshot of the benchmark ：
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/197434fb-2818-4e88-bcfc-70cedf9d0d80">
<img width="1773" alt="image" src="https://github.com/user-attachments/assets/c82994c7-9857-4abf-b46e-f358f8adaf36">




The results show the changes are working as expected,

Let me know if you need any additional information or clarification.

2024-10-28 03:06 UTC, MooreZheng reviewed
This pull request contains 10 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. In the final stage, @XueSongTap  can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

2024-10-28 14:03 UTC, XueSongTap commented
@MooreZheng I have already addressed this concern by squashing all commits into a single commit using rebase. The changes are now consolidated into one cohesive commit for better maintenance and clearer history. Please review the updated changes.

2024-10-29 16:10 UTC, MooreZheng commented
/lgtm

2024-10-29 16:11 UTC, MooreZheng commented
@XueSongTap might need one more review from @hsj576

2024-10-30 02:22 UTC, hsj576 commented
/lgtm

2024-10-30 02:42 UTC, CreativityH commented
/lgtm

2024-10-30 12:52 UTC, MooreZheng requested changes
To avoid conflicts, need to change print() using logger

2024-10-30 14:11 UTC, XueSongTap commented
@MooreZheng hi, i've changed print() using logger. Could you please review this PR? Let me know if you need any additional information or clarification.

2024-10-30 14:18 UTC, MooreZheng commented
/lgtm

2024-10-30 14:18 UTC, MooreZheng commented
/approve

2024-10-30 14:19 UTC, MooreZheng approved these changes
All concerns are fixed. Well done and congratulations to @XueSongTap

2024-10-30 14:19 UTC, merged

2026-01-29 12:28 UTC, MooreZheng commented
Related issue and PR: https://github.com/kubeedge/ianvs/issues/94 https://github.com/kubeedge/ianvs/pull/121 https://github.com/kubeedge/ianvs/pull/127 https://github.com/kubeedge/ianvs/pull/150