OSPP: Smart Coding benchmark suite: built on KubeEdge-lanvs
kubeedge/ianvs pull request #159
Opened 2024-10-25 19:32 UTC by safe-b

This PR is the implementation of #98

2024-10-26 03:18 UTC, MooreZheng requested changes
The proposals are not needed in this implementation PR. Shall move the proposal to the proposal PR, i.e., https://github.com/kubeedge/ianvs/pull/120

Besides, all the content written in Chinese should be translated into English to facilitate international understanding and usage.

2024-10-26 03:18 UTC, MooreZheng commented on docs/proposals/scenarios/Smart_Coding/Smart Coding benchmark suite Proposal_zh.md
> +# 背景
The proposals are not needed in this implementation PR. Shall keep the proposal in the proposal PR, i.e., https://github.com/kubeedge/ianvs/pull/120

Besides, all the content written in Chinese should be translated into English to facilitate international understanding and usage.

2024-10-26 03:18 UTC, MooreZheng commented on docs/proposals/test-reports/Smart Coding benchmark suite Proposal_zh.md
> +大型语言模型（LLM）在代码生成、自动编程、代码分析等任务中展现出了强大的能力，但这些模型通常是在通用代码数据上训练的，往往不能充分利用实际场景中软件工程师的协作和反馈。为了构建更加智能高效的代码生态，需要建立协作代码数据集和评测基准，促进LLM与软件工程师的紧密协作。本项目旨在基于开源边缘计算框架KubeEdge-Ianvs构建LLM协作代码智能体对齐数据集和评测基准。该数据集将包括软件工程师
The proposals are not needed in this implementation PR. Shall keep the proposal in the proposal PR, i.e., https://github.com/kubeedge/ianvs/pull/120

Besides, all the content written in Chinese should be translated into English to facilitate international understanding and usage.

2024-10-26 03:18 UTC, MooreZheng commented on examples/smart_coding/smart_coding_learning_bench/comment/testenv/llm_judgement.py
> +    # 使用正则表达式匹配综合得分及其分数
In comment/testenv/llm_judgement.py, the content written in Chinese should be translated into English to facilitate international understanding and usage.

2024-10-26 03:18 UTC, MooreZheng commented on examples/smart_coding/smart_coding_learning_bench/issue/testenv/llm_judgement.py
> +    # 使用正则表达式匹配综合得分及其分数
In issue/testenv/llm_judgement.py, the content written in Chinese should be translated into English to facilitate international understanding and usage.

2024-10-26 03:24 UTC, MooreZheng requested changes
Besides, there are also CI issues that remain to be solved, see https://github.com/kubeedge/ianvs/actions/runs/11524309022/job/32095357988?pr=159

For example 
```
Run if [ "3.7" = "3.9" ]; then
************* Module core.testenvmanager.dataset.dataset
core/testenvmanager/dataset/dataset.py:22:0: C0301: Line too long (106/100) (line-too-long)
core/testenvmanager/dataset/dataset.py:22:0: E06[11](https://github.com/kubeedge/ianvs/actions/runs/11524309022/job/32095357988?pr=159#step:5:12): No name 'JsonlDataParse' in module 'sedna.datasources' (no-name-in-module)
core/testenvmanager/dataset/dataset.py:22:0: E0611: No name 'JSONMetaDataParse' in module 'sedna.datasources' (no-name-in-module)
core/testenvmanager/dataset/dataset.py:28:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
core/testenvmanager/dataset/dataset.py:19:0: W0611: Unused import json (unused-import)

-----------------------------------
Your code has been rated at 9.92/10

Error: Process completed with exit code 30.
```

2024-10-26 07:04 UTC, safe-b commented
> 此外，还有一些 CI 问题有待解决，请参阅 https://github.com/kubeedge/ianvs/actions/runs/11524309022/job/32095357988?pr=159
> 
> 例如
> 
> ```
> Run if [ "3.7" = "3.9" ]; then
> ************* Module core.testenvmanager.dataset.dataset
> core/testenvmanager/dataset/dataset.py:22:0: C0301: Line too long (106/100) (line-too-long)
> core/testenvmanager/dataset/dataset.py:22:0: E06[11](https://github.com/kubeedge/ianvs/actions/runs/11524309022/job/32095357988?pr=159#step:5:12): No name 'JsonlDataParse' in module 'sedna.datasources' (no-name-in-module)
> core/testenvmanager/dataset/dataset.py:22:0: E0611: No name 'JSONMetaDataParse' in module 'sedna.datasources' (no-name-in-module)
> core/testenvmanager/dataset/dataset.py:28:0: R0902: Too many instance attributes (9/7) (too-many-instance-attributes)
> core/testenvmanager/dataset/dataset.py:19:0: W0611: Unused import json (unused-import)
> 
> -----------------------------------
> Your code has been rated at 9.92/10
> 
> Error: Process completed with exit code 30.
> ```

已经按照 https://github.com/kubeedge/ianvs/actions/runs/11524309022/job/32095357988?pr=159进行了修改，对dataset.py文件进行了补充

2024-10-26 07:35 UTC, MooreZheng requested changes
New CI errors see https://github.com/kubeedge/ianvs/actions/runs/11529775773/job/32099094184?pr=159

```
Run if [ "3.7" = "3.9" ]; then
************* Module core.testenvmanager.dataset.dataset
core/testenvmanager/dataset/dataset.py:468:0: C0304: Final newline missing (missing-final-newline)

-----------------------------------
Your code has been rated at 9.99/10

Error: The operation was canceled.
```

2024-10-26 07:39 UTC, safe-b commented
> 新的 CI 错误见 https://github.com/kubeedge/ianvs/actions/runs/11529775773/job/32099094184?pr=159
> 
> ```
> Run if [ "3.7" = "3.9" ]; then
> ************* Module core.testenvmanager.dataset.dataset
> core/testenvmanager/dataset/dataset.py:468:0: C0304: Final newline missing (missing-final-newline)
> 
> -----------------------------------
> Your code has been rated at 9.99/10
> 
> Error: The operation was canceled.
> ```

明白，好像是我的尾行格式设置有误，操作系统格式问题，正在修改

2024-10-26 07:39 UTC, MooreZheng requested changes
> The proposals are not needed in this implementation PR. Shall move the proposal to the proposal PR, i.e., #120

Kindly remind: 1) need to remove proposals in implementation PR; 2) translate words in Chinese. See comments in https://github.com/kubeedge/ianvs/pull/159#pullrequestreview-2397030720

2024-10-26 07:42 UTC, safe-b commented
> Reference in

相关proposal已经删除，后续提交仅更新代码

2024-10-28 03:20 UTC, MooreZheng requested changes
This pull request contains 10 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. 

After all the comments are tackled, in the final stage, @safe-b can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

2024-10-28 03:20 UTC, MooreZheng commented on docs/proposals/test-reports/Smart Coding benchmark suite Proposal_zh.md
> +# 背景
As mentioned, proposals shall be kept in the proposal PR. If it is needed in the test reports, then this document shall be written as test reports like [this link](https://ianvs.readthedocs.io/en/latest/proposals/test-reports/testing-single-task-learning-in-industrial-defect-detection-with-pcb-aoi.html).

2024-10-28 03:20 UTC, MooreZheng commented on docs/proposals/test-reports/Smart Coding benchmark suite Proposal_zh.md
> +# 背景
In test reports, all the content written in Chinese should be translated into English to facilitate international understanding and usage.

2024-10-29 16:15 UTC, MooreZheng requested changes
Comments include
1. fix all statements written in Chinese

2. This branch has conflicts that must be resolved
Use the [web editor](https://github.com/kubeedge/ianvs/pull/159/conflicts) or the  to resolve conflicts.
Conflicting files
core/testenvmanager/dataset/dataset.py

3. This pull request contains 10 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. After all the comments are tackled, in the final stage, @safe-b can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

2024-10-30 14:01 UTC, MooreZheng requested changes
Conflicts and English issues have been fixed. 

However, this pull request contains 17 commits, which might make maintenance difficult, considering the number of contributors, pull requests, and their commits in KubeEdge Ianvs recently. After all the comments are tackled, in the final stage, @safe-b can squash the commits into one using [rebase techniques](https://blog.kinboy.wang/2019/04/09/Git-%E5%8E%8B%E7%BC%A9%E5%A4%9A%E4%B8%AAcommit%E4%B8%BA%E5%8D%95%E4%B8%AAcommit/).

2024-10-31 10:34 UTC, hsj576 approved these changes
/lgtm

2024-10-31 10:34 UTC, MooreZheng commented
/lgtm

2024-10-31 10:35 UTC, MooreZheng commented
/approve

2024-10-31 10:35 UTC, MooreZheng approved these changes
All concerns are fixed. Well done! @safe-b

2024-10-31 10:36 UTC, merged

2026-02-04 02:04 UTC, MooreZheng commented
Related issue and PR: https://github.com/kubeedge/ianvs/issues/98 https://github.com/kubeedge/ianvs/pull/120 https://github.com/kubeedge/ianvs/pull/159