Implementation of Cloud-robotics singletask_learning
kubeedge/ianvs pull request #168
Opened 2024-12-06 10:12 UTC by aryan0931

**What type of PR is this?**
/kind design

**What this PR does / why we need it**:
Implementation of Cloud-robotics singletask_learning

**Which issue(s) this PR fixes**:
Fixes #123

2024-12-06 10:48 UTC, MooreZheng reviewed
Good to see the implementation~ @aryan0931 is suggested to introduce the implementation for KubeEdge Reviewers on the routine meeting and @hsj576 might want to take a deeper look at the implementation

2024-12-27 10:38 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testalgorithms/basemofel.py
> +        model_url = '/home/wxc/dev/ianvs/models/model_best_mapi_only.pth'
The model_url is hardcoded in the load function which would bypass the parameter, which should be revised.

2024-12-27 10:42 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testalgorithms/basemofel.py
> +            # if not self.trainer.args.no_val and \
Considering Clean Code: remove redundant codes instead of making them as comment

2024-12-27 10:43 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testalgorithms/basemofel.py
> +        print("Total epoches:", self.trainer.args.epochs)
should replace print using loggers

2024-12-27 10:43 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testenv/accuracy.py
> +    print("CPA:{}, mIoU:{}, fwIoU: {}".format(CPA, mIoU, FWIoU))
should replace print using loggers

2024-12-27 11:06 UTC, MooreZheng requested changes
It is a basic version of the multi-modal model project. Before merging the PR, 
1) as mentioned at the routine meeting, an output demonstration is needed. 
2) the above comments should be fixed.

2025-01-10 03:12 UTC, MooreZheng commented
Another new LFX term is coming. Any progress for this PR? @aryan0931

2025-01-10 04:53 UTC, aryan0931 commented
> Another new LFX term is coming. Any progress for this PR? @aryan0931 

Sorry sir I was not well from some days, I will raise the final Pull request till Sunday.

2025-01-13 21:25 UTC, closed without merging

2025-01-16 01:23 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testalgorithms/basemofel.py
> +        model_url = '/home/wxc/dev/ianvs/models/model_best_mapi_only.pth'
Not solved yet

2025-01-16 01:24 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testalgorithms/basemofel.py
> +            # if not self.trainer.args.no_val and \
Not solved yet

2025-01-16 01:26 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testalgorithms/basemofel.py
> +        print("Total epoches:", self.trainer.args.epochs)
Not fully solved yet. There are still "print" functions in the code.

2025-01-16 01:27 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testalgorithms/basemofel.py
> +# Copyright 2022 The KubeEdge Authors.
Not resolved yet. The file name is still "basemofel".

2025-01-16 01:37 UTC, MooreZheng commented on examples/Cloud_Robotics/singletask_learning_bench/Semantic_Segmentation/testenv/accuracy.py
> +    print("CPA:{}, mIoU:{}, fwIoU: {}".format(CPA, mIoU, FWIoU))
The solution of metrics of the new version from PR #176 looks fine to me