Add proposal for Cloud-robotics dataset
kubeedge/ianvs pull request #69
Opened 2023-06-14 08:29 UTC by hsj576

**What type of PR is this?**
Proposal for Cloud-robotics dataset

2023-07-06 07:11 UTC, jaypume requested changes

2023-07-06 07:11 UTC, jaypume commented on docs/proposals/scenarios/Cloud-Robotics/pic/end.png
It is suggest to pixelate the girl's face to protect her privacy.

2023-07-10 13:06 UTC, hsj576 commented on docs/proposals/scenarios/Cloud-Robotics/pic/end.png
> It is suggest to pixelate the girl's face to protect her privacy.

Ok, I will pixelate the girl's face.

2023-07-20 06:27 UTC, jaypume commented
/lgtm

2023-07-20 06:30 UTC, merged