OSPP: Implementation of a Class Incremental Learning Algorithm Evaluation System based on Ianvs
kubeedge/ianvs pull request #85
Opened 2023-10-31 02:06 UTC by qxygxt

2023-10-31 03:39 UTC, Frank-lilinjie commented
lgtm

2023-10-31 07:05 UTC, jaypume requested changes

2023-10-31 07:05 UTC, jaypume commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/mypath.py
> +class Path(object):
Hardcoded path, it is suggested to return these path without the personal path like 'robo' 'm0063' etc..

2023-10-31 07:05 UTC, jaypume commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/sedna_evaluate.py
> +os.environ['BACKEND_TYPE'] = 'PYTORCH'
remove unused lines

2023-10-31 07:05 UTC, jaypume commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/sedna_predict.py
> +# os.environ["UNSEEN_SAVE_URL"] = "s3://kubeedge/sedna-robo/unseen_samples/"
please remove unused lines

2023-10-31 07:05 UTC, jaypume commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/utils/args.py
> +        self.savedir = '/home/QXY/dataset/save'
Hardcoded path should not be committed here, suggest to use the relative path.

2023-10-31 07:05 UTC, jaypume commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/utils/iouEval.py
> +        # for i in range(0, x.size(0)):
unused lines should be removed.

2023-10-31 07:05 UTC, jaypume commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/utils/loss.py
> +    a = torch.rand(1, 3, 7, 7).cuda()
What is the number '1 3 7 7 'meaning? if these lines is used for debug, please remove them.

2023-10-31 11:42 UTC, jaypume commented
/lgtm

2023-10-31 11:43 UTC, jaypume commented
/approve

2023-10-31 11:50 UTC, merged

2026-05-23 18:09 UTC, abhisheksainimitawa reviewed
## PR Review: OSPP Implementation of Class Incremental Learning Algorithm Evaluation System

**Contributor:** [@abhisheksainimitawa](https://github.com/abhisheksainimitawa) | LFX Mentorship 2026 Term 2 Pre-test Task 2

---

**What it does:** Foundational OSPP implementation that created the MDIL-SS lifelong learning benchmark from scratch — 5386 lines added across the entire example directory (then named `class_increment_semantic_segmentation`). Contributions:
- ERFNet model architecture
- Custom dataloaders for Cityscapes/Synthia/Cloud-Robotics
- Task definition and allocation modules
- Sedna bridge scripts (`basemodel.py`, `sedna_evaluate.py`, `sedna_train.py`)
- BWT/FWT/MATRIX metric computation
- All three YAML configuration files (`benchmarkingjob.yaml`, `testenv.yaml`, `test_algorithm.yaml`)

**Merge decision: Correct.** The foundational code is the right starting point and the algorithmic design is sound. However, the ERFNet code was ported from an upstream GPU-only research codebase without adapting it for cross-platform use, planting the seeds of every hardware and library compatibility bug that still exists today.

---

**Finding 1 — CUDA hardcoding (issue [#471](https://github.com/kubeedge/ianvs/issues/471)):**
Every model instantiation and tensor transfer in `train.py`, `trainer.py`, and `basemodel.py` uses `.cuda()` directly with no device-detection fallback:
```python
# train.py:
model = ERFNet(NUM_CLASSES).cuda()
inputs = inputs.cuda()
labels = labels.cuda()
```
On any machine without a CUDA GPU (macOS, CPU-only CI), this raises `RuntimeError: No CUDA GPUs are available` before training begins.

**Finding 2 — Deprecated torchvision API (issue [#472](https://github.com/kubeedge/ianvs/issues/472) Bug A):**
`ERFNet/utils/summaries.py` uses the `range=` keyword for `torchvision.utils.make_grid()` at 4 call sites:
```python
# summaries.py (4 sites):
make_grid(image_tensor, 3, normalize=False, range=(0, 255))
```
This keyword was renamed to `value_range=` in torchvision 0.8. Any environment with torchvision >= 0.8 crashes with `TypeError: make_grid() got an unexpected keyword argument 'range'`.

**Finding 3 — DataLoader multiprocessing crash (issue [#472](https://github.com/kubeedge/ianvs/issues/472) Bug B):**
ERFNet uses bare relative imports (`from dataloaders import ...`) that require the package root on `sys.path`. When `num_workers=4`, PyTorch spawns subprocess workers that start in a different working directory, causing `ModuleNotFoundError` in every worker. Fix: `sys.path.insert(0, ERFNet_dir)` in `basemodel.py` before any ERFNet import.

**Finding 4 — TaskAllocation interface mismatch (issue [#473](https://github.com/kubeedge/ianvs/issues/473)):**
`task_allocation_by_domain.py` defines the allocator with two arguments:
```python
class TaskAllocationByOrigin:
    def __call__(self, task_extractor, samples):
```
The Sedna `LifelongLearning` framework calls it as `allocator(samples)` — one argument, not two. This raises `TypeError: __call__() missing 1 required positional argument: 'samples'` at inference time.

**Finding 5 — Standalone script domain divergence (issues [#463](https://github.com/kubeedge/ianvs/issues/463), [#466](https://github.com/kubeedge/ianvs/issues/466)):**
`sedna_evaluate.py` and `sedna_train.py` were copied from a 2-domain example with `origins: ["real", "sim"]`. The MDIL-SS benchmark is a 3-domain problem (`["Cityscapes", "Synthia", "Cloud-Robotics"]`). Running these scripts directly produces incorrect task allocation — evaluation across 2 domains instead of 3, with Cloud-Robotics data silently misclassified.

**Finding 6 — `mode: "no-inference"` in `testenv.yaml` activates 5 API mismatches (issues [#284](https://github.com/kubeedge/ianvs/issues/284), [#285](https://github.com/kubeedge/ianvs/issues/285), [#461](https://github.com/kubeedge/ianvs/issues/461), [#462](https://github.com/kubeedge/ianvs/issues/462), [#470](https://github.com/kubeedge/ianvs/issues/470)):**
PR #85's `testenv.yaml` sets `mode: "no-inference"` from the initial commit (`6e8a115`). This directs the lifelong learning pipeline to the `no-inference` branch in `lifelong_learning.py`, which contains Sedna API calls that do not exist: `job.my_evaluate()` (issue [#284](https://github.com/kubeedge/ianvs/issues/284)), `job.my_inference()` (issue [#461](https://github.com/kubeedge/ianvs/issues/461)), and `job.inference_2()` (issue [#470](https://github.com/kubeedge/ianvs/issues/470)). A 3-value unpack of `job.evaluate()`'s single-dict return (issue [#285](https://github.com/kubeedge/ianvs/issues/285)) and a division-by-zero in the task-average accumulation loop (issue [#462](https://github.com/kubeedge/ianvs/issues/462)) also exist in this path. These five API issues are the active blockers once the Category A path failures are resolved.

**Impact on our example today:** All six findings above are still present in `robot-cityscapes-synthia`. The no-inference API mismatches (#284, #285, #461, #462, #470) are the next active blockers in the core framework once path failures are fixed.

**Recommendation:** File fix PRs for [#471](https://github.com/kubeedge/ianvs/issues/471), [#472](https://github.com/kubeedge/ianvs/issues/472), and [#473](https://github.com/kubeedge/ianvs/issues/473) as a coordinated set. Fix the no-inference API mismatches in `lifelong_learning.py`. File a standalone-script fix for [#463](https://github.com/kubeedge/ianvs/issues/463) and [#466](https://github.com/kubeedge/ianvs/issues/466) once the main execution path is restored.

---

### What Makes This Review Unique

This review confirmed 5 runtime bugs through `grep -rn` pattern matching, source-level tracing, and `testenv.yaml` configuration analysis — none of which were documented in any issue at the time of PR #85's merge:

- **CUDA hardcoding confirmed at 2 sites:** `self.cuda = True` in both `TrainArgs` and `EvalArgs` in `args.py` (lines 34 and 61), with no `torch.cuda.is_available()` guard — crashes on any CPU-only machine before training begins.
- **Deprecated torchvision keyword confirmed at 4 sites:** `range=` in all 4 `make_grid()` calls in `summaries.py` — renamed to `value_range=` in torchvision 0.8, causing `TypeError` on any modern environment.
- **DataLoader worker import failure traced:** bare relative ERFNet imports fail in worker subprocesses because `sys.path` is not set — fix requires `sys.path.insert(0, ERFNet_dir)` in `basemodel.py` before any ERFNet import.
- **TaskAllocation interface mismatch identified:** `TaskAllocationByOrigin.__call__(self, task_extractor, samples)` is invoked by Sedna as `allocator(samples)` — a two-argument method called with one, raising `TypeError` at inference time.
- **`mode: "no-inference"` in `testenv.yaml` activates 5 API mismatches:** `git show 6e8a115` confirms PR #85 set `mode: "no-inference"` in `testenv.yaml`. This routes the pipeline to the `no-inference` branch which calls `job.my_evaluate()` (issue [#284](https://github.com/kubeedge/ianvs/issues/284)), `job.my_inference()` (issue [#461](https://github.com/kubeedge/ianvs/issues/461)), and `job.inference_2()` (issue [#470](https://github.com/kubeedge/ianvs/issues/470)) — none of which exist in the Sedna API. A 3-value unpack (issue [#285](https://github.com/kubeedge/ianvs/issues/285)) and a division-by-zero (issue [#462](https://github.com/kubeedge/ianvs/issues/462)) are also in this path.

---

### A. Reproduce (PR #85 — merged into main via `6e8a115`)

PR #85 is already part of main. All six findings above are verifiable against the current codebase.

**A-1. Merge commit confirmed in git history**

```bash
git log --oneline --all | grep "6e8a115"
# 6e8a115 Merge pull request #85 from qxygxt/main
```

**A-2. CUDA hardcoding still present today (issue [#471](https://github.com/kubeedge/ianvs/issues/471))**

```bash
grep -rn "cuda = True" examples/robot-cityscapes-synthia/lifelong_learning_bench/semantic-segmentation/testalgorithms/erfnet/ERFNet/utils/args.py
```

```
3 [...]

2026-05-28 10:10 UTC, abhisheksainimitawa commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/utils/args.py
> +        self.cuda = True
**CUDA hardcoding — no device-detection fallback (issue [#471](https://github.com/kubeedge/ianvs/issues/471))**

`self.cuda = True` is set unconditionally in both `TrainArgs` (line 34) and `EvalArgs` (line 61) with no `torch.cuda.is_available()` guard. On any CPU-only machine (macOS, CPU-only CI), this causes `RuntimeError: No CUDA GPUs are available` before training begins.

**Suggested fix:**
```python
self.cuda = torch.cuda.is_available()
```

This same class of fix is demonstrated in PR #441's sibling example — replacing unconditional `.cuda()` calls with device-detection guards.

2026-05-28 10:11 UTC, abhisheksainimitawa commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/ERFNet/utils/summaries.py
> +                                                           dataset=dataset), 3, normalize=False, range=(0, 255))
**Deprecated torchvision keyword (issue [#472](https://github.com/kubeedge/ianvs/issues/472) Bug A)**

The `range=` keyword argument to `torchvision.utils.make_grid()` was renamed to `value_range=` in torchvision 0.8. This call site (and lines 25, 35, 38) all pass `range=(0, 255)`, which raises `TypeError: make_grid() got an unexpected keyword argument 'range'` in any modern environment.

**Suggested fix for all 4 sites:**
```python
# Change:
make_grid(..., normalize=False, range=(0, 255))
# To:
make_grid(..., normalize=False, value_range=(0, 255))
```

2026-05-28 10:11 UTC, abhisheksainimitawa commented on examples/class_increment_semantic_segmentation/lifelong_learning_bench/testalgorithms/erfnet/task_allocation_by_domain.py
> +    def __call__(self, task_extractor, samples: BaseDataSource):
**TaskAllocation interface mismatch — 2-arg callable invoked with 1 (issue [#473](https://github.com/kubeedge/ianvs/issues/473))**

`TaskAllocationByOrigin.__call__` is defined with signature `(self, task_extractor, samples)` (2 required arguments beyond `self`), but the Sedna `LifelongLearning` framework invokes the allocator as `allocator(samples)` — passing only 1 argument. This raises:

```
TypeError: __call__() missing 1 required positional argument: 'samples'
```

at inference time for any run through the task allocation path.

**Suggested fix:**
```python
def __call__(self, samples: BaseDataSource):
    # remove task_extractor from signature
```

2026-05-29 15:42 UTC, phantom-712 commented
# PR #85 - Detailed Review

**Recommendation: Historical Reference - No Action Required (Merged)**


#### Introduction

PR #85 is the OSPP foundational implementation that introduced two components still critical today: the `metrics.py` module - containing `bwt_func`, `fwt_func`, and the BWT/FWT matrix computation - and the MDIL-SS example as the first working `LifelongLearning` paradigm implementation in Ianvs. Understanding this PR is prerequisite to understanding every current bug.

#### Module Details

**Files changed:** `metrics.py` (new file), `examples/robot-cityscapes-synthia/lifelong_learning_bench/` (new example), and associated testenv configs. No modification to `lifelong_learning.py` - the paradigm controller was pre-existing.

**Core modification:** `metrics.py` is a core module under `core/testcasecontroller/algorithm/paradigm/lifelong_learning/`. This was appropriate - BWT/FWT are paradigm-level metrics that must be computed centrally, not per-example.

#### Historical Attribution - `my_eval()` Origin

This PR does **not** introduce `my_eval()`. The method was added by hsj576 in commit `778db39` after this PR's merge, reflecting the internal Sedna fork API contract. PR #85 only added the OSPP metrics infrastructure. This is confirmed by the patch file: no `my_eval` string appears in PR #85's diff.

#### Finding - 2-Domain vs 3-Domain API Divergence

As analyzed by `prior community reviews` (Issue 459 / 463), this PR introduced a silent behavioral divergence in the standalone scripts. `sedna_evaluate.py` and `sedna_train.py` configure task allocation with stale 2-domain origins (`["real", "sim"]`), copied from the older `robot/lifelong_learning_bench` example:

```python
# sedna_evaluate.py and sedna_train.py:
task_allocation_by_origin = {
    "real": ...,
    "sim": ...
}
```

However, the MDIL-SS `robot-cityscapes-synthia` benchmark actually operates on a 3-domain YAML configuration (`real`, `sim`, `cityscapes`). This hardcoded 2-domain API in the standalone scripts makes them fundamentally incompatible with the 3-domain configuration they test.

#### Root Cause Significance - Layer 7 / Gap B

The `bwt_func` at `metrics.py:102-121` (from this PR) accesses `system_metric_info[MATRIX]["all"]` without guarding against an empty MATRIX:

```python
# metrics.py:109 - from PR #85, unguarded:
for i in range(len(matrix["all"])):
    bwt += matrix["all"][i][i]  # KeyError: 'all' if MATRIX is empty
```

This becomes the Layer 7 blocker after PR #301 merges: PR #301 removes the `tasks_detail` iteration that was (incorrectly) populating MATRIX as a side effect. After #301, MATRIX stays empty → `bwt_func` raises `KeyError: 'all'`. The fix (Gap B) must add a guard in this function.

#### Reproduce: Smooth (Merged - Historical Baseline)

```bash
# PR #85 merged 2023. Reproducing its contribution by inspecting the metrics module:
$ python3 -c "
import sys; sys.path.insert(0, 'E:/Ianvs/08_REPOSITORIES/ianvs')
from core.testcasecontroller.metrics.metrics import bwt_func
print('bwt_func imported from PR #85 metrics module - confirmed present')
# Layer 7 crash verification (Gap B):
bwt_func({'matrix': {}})  # empty MATRIX scenario
"
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "core\testcasecontroller\metrics\metrics.py", line 106, in bwt_func
    _, BWT_score, _ = compute("all", info["all"])
                                     ~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

#### Logs Summary

```
Component                     | Source  | Status Today
------------------------------|---------|---------------------------
metrics.py (bwt_func, fwt_func) | PR #85  | Present - latent KeyError at MATRIX["all"]
MDIL-SS example               | PR #85  | Present - path bugs fixed by #366
my_eval() method              | PR #85  | NOT present - added later by hsj576
lifelong_learning.py changes  | PR #85  | None - not touched
```

---